// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Models;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(EFDdataContext))]
    partial class EFDdataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication2.Models.Agent", b =>
                {
                    b.Property<int>("Agent_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agent_company");

                    b.Property<string>("Agent_email");

                    b.Property<string>("Agent_name");

                    b.Property<string>("Agent_password");

                    b.Property<string>("Agent_phone");

                    b.HasKey("Agent_id");

                    b.ToTable("Agent");
                });

            modelBuilder.Entity("WebApplication2.Models.Claims", b =>
                {
                    b.Property<int>("Claims_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agent_id");

                    b.Property<int>("Approved_amount");

                    b.Property<int>("Claimed_amount");

                    b.Property<int>("Cust_id");

                    b.Property<int>("Policy_id");

                    b.Property<int>("Remarks");

                    b.Property<int>("Vehicle_id");

                    b.HasKey("Claims_id");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("WebApplication2.Models.Cust", b =>
                {
                    b.Property<int>("Cust_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agent_id");

                    b.Property<string>("Cust_gender");

                    b.Property<string>("Cust_license");

                    b.Property<string>("Cust_name");

                    b.Property<string>("Cust_nationality");

                    b.Property<string>("Cust_pass");

                    b.HasKey("Cust_id");

                    b.ToTable("Custs");
                });

            modelBuilder.Entity("WebApplication2.Models.Policy", b =>
                {
                    b.Property<int>("Policy_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Policy_amount");

                    b.Property<string>("Policy_number");

                    b.Property<string>("Policy_type");

                    b.Property<string>("Policy_valid_date");

                    b.Property<int>("cust_id");

                    b.HasKey("Policy_id");

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("WebApplication2.Models.Vehicle", b =>
                {
                    b.Property<int>("Vehicle_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cust_id");

                    b.Property<string>("Vehicle_color");

                    b.Property<string>("Vehicle_company");

                    b.Property<string>("Vehicle_model");

                    b.Property<string>("Vehicle_pending_fines");

                    b.Property<string>("Vehicle_plate_num");

                    b.Property<string>("Vehicle_reg_date");

                    b.HasKey("Vehicle_id");

                    b.ToTable("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
